// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsrsI0qbkdgQeR4Cy9i6XlHbA3yrXOis',
    appId: '1:303510216622:web:83c381249300796dc9f23f',
    messagingSenderId: '303510216622',
    projectId: 'in-lab-activity-reciept-app',
    authDomain: 'in-lab-activity-reciept-app.firebaseapp.com',
    storageBucket: 'in-lab-activity-reciept-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA35QSr2NZbdgOs6BhAtyTbpdjnEBl-GEU',
    appId: '1:303510216622:android:3834d3a24f9106a4c9f23f',
    messagingSenderId: '303510216622',
    projectId: 'in-lab-activity-reciept-app',
    storageBucket: 'in-lab-activity-reciept-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2A9peh-X051nE5av9o_JPmNxtkLQZ4fk',
    appId: '1:303510216622:ios:81197b9e0c934b30c9f23f',
    messagingSenderId: '303510216622',
    projectId: 'in-lab-activity-reciept-app',
    storageBucket: 'in-lab-activity-reciept-app.appspot.com',
    iosClientId: '303510216622-a3b1em9hc1fogsafh5r3nkj23gmtokim.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivityRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2A9peh-X051nE5av9o_JPmNxtkLQZ4fk',
    appId: '1:303510216622:ios:81197b9e0c934b30c9f23f',
    messagingSenderId: '303510216622',
    projectId: 'in-lab-activity-reciept-app',
    storageBucket: 'in-lab-activity-reciept-app.appspot.com',
    iosClientId: '303510216622-a3b1em9hc1fogsafh5r3nkj23gmtokim.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivityRecipesApp',
  );
}
